sudo: false
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

before_install: phpenv config-add travis-cfg.ini

before_script:
  - composer self-update && composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
